name = "soroban-events-queue"
usage_model = "bundled"
main = "src/worker.ts"
compatibility_date = "2023-08-01"
compatibility_flags = [
    "durable_object_alarms",
    "durable_object_fetch_allows_relative_url",
]
logpush = true
send_metrics = true
workers_dev = true

kv_namespaces = [
  { binding = "EVENTS_KV", id = "576bc6ec862c42ffbf7a11da3eecf252", preview_id = "0x000000000000000000000000000000" }
]

[[d1_databases]]
binding = "EVENTS_SQL"
database_name = "soroban-events"
database_id = "111808a1-cd2d-4b19-ac8c-cdab3660efa3"

[[queues.producers]]
queue = "event-listener"
binding = "QUEUE"

[[queues.consumers]]
queue = "event-listener"
dead_letter_queue = "event-listener-dlq"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 5

[[queues.consumers]]
queue = "event-listener-dlq"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 5

[triggers]
crons = ["* * * * *"]

[[migrations]]
tag = "v1"
new_classes = ["EventPoll"]

[[durable_objects.bindings]]
name = "EVENTPOLL"
class_name = "EventPoll"

[[r2_buckets]]
bucket_name = "event-listener-dlq-bucket"
binding = "DLQ_BUCKET"